sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: YOUR ACCESS KEY ID
    access-key-secret: YOUR ACCESS KEY SECRET
    bucket-name: hsalg
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx2313871b58e39ebf
    secret: f1eb3f6434889e346b5150d780d99dba
    # 商户号
    mchid: 1561414331
    # 对应的证书的序列号
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
 #   privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
  #  weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    #支付成功回调 内网穿透临时域名 + /notify/paySuccess(Controller层接口)
    notifyUrl:  http://3cff5640.r7.cpolar.cn/notify/paySuccess
    #退款成功回调 内网穿透临时域名 + /notify/refundSuccess(Controller层接口)
    refundNotifyUrl:  http://3cff5640.r7.cpolar.cn/notify/refundSuccess

